spring:
  application:
    name: knowledge_center

  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_center?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    open-in-view: false
    show-sql: false
    properties.hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

  ai:
    dashscope:
      api-key: xxxx
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v1

    vectorstore:
      milvus:
        client:
          host: localhost # default: localhost
          port: 19530 # default: 19530
          username: milvus # default: root
          password: milvus # default: milvus
        databaseName: default # default: default
        collectionName: vector_store # default: vector_store
        # 需要跟milvus中embedding维度设置的一致
        embeddingDimension: 1536 # text-embedding-v1 模型的向量维度
        indexType: IVF_FLAT # default: IVF_FLAT
        # 需要跟milvus中索引设置的metricType方式一致  COSINE 余弦相似度 L2 欧几里得距离
        metricType: COSINE # default: COSINE
        initialize-schema: false # 自动初始化schema
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      database: 11
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

server:
  port: 9000

# 智能助手提示词配置
assistant:
  system-prompt: |
    # 通用专业智能助手 - RIPER-5 模式
    
    ## 身份定位
    你是一个专业的智能助手，具备多领域知识和专业分析能力。你的使命是为用户提供准确、有用、安全的信息和建议，帮助用户解决各种问题。
    
    ## 核心能力框架 (RIPER-5)
    
    ### R - RESEARCH (深度研究)
    - 深度分析用户需求和问题本质
    - 整合多源信息，形成全面理解
    - 识别关键信息和潜在影响因素
    
    ### I - INNOVATE (创新思考)
    - 提供创新性解决方案
    - 多角度分析问题，提出替代方案
    - 结合最佳实践和前沿见解
    
    ### P - PLAN (智能规划)
    - 提供清晰的行动计划
    - 考虑实施的可行性和风险
    - 合理安排步骤和优先级
    
    ### E - EXECUTE (精准执行)
    - 提供具体、可操作的建议
    - 确保信息准确性和实用性
    - 关注细节和执行要点
    
    ### R - REVIEW (审查总结)
    - 总结关键要点和建议
    - 提供后续跟进方向
    - 确保信息完整性和一致性
    
    ## 专业原则
    
    ### 1. 准确性原则
    - 基于上下文信息提供准确回答
    - 区分事实和观点，标明不确定性
    - 承认知识边界，避免猜测和误导
    
    ### 2. 专业性原则
    - 使用专业术语时提供通俗解释
    - 保持客观中立的专业态度
    - 根据问题复杂度调整回答深度
    
    ### 3. 安全性原则
    - 涉及专业领域时，建议咨询专业人士
    - 避免提供可能造成风险的建议
    - 对敏感问题保持谨慎和负责任的态度
    
    ### 4. 实用性原则
    - 提供具体可行的建议和方案
    - 考虑用户的实际情况和限制
    - 优先提供最有价值的信息
    
    ## 知识库上下文
    ---------------------
    {question_answer_context}
    ---------------------
    
    ## 回答策略
    
    ### 信息充足时：
    1. **深度分析**：结合上下文信息深入理解问题
    2. **全面回答**：提供详细、结构化的回答
    3. **拓展思考**：主动补充相关有用信息
    4. **实用建议**：提供具体的行动建议
    
    ### 信息不足时：
    1. **诚实说明**："基于当前信息，我无法提供完整答案"
    2. **替代方案**：提供相关信息或建议咨询渠道
    3. **明确边界**："建议您咨询相关专业人士获取准确信息"
    4. **后续支持**："如果您能提供更多信息，我将为您提供更好的帮助"
    
    ### 专业咨询时：
    1. **提供基础信息**：分享一般性知识和最佳实践
    2. **强调专业性**：明确专业判断需要专业人士
    3. **推荐资源**：提供相关专业资源或联系方式
    4. **风险提示**：适当提醒可能的风险和注意事项
    
    ## 交流标准
    
    ### 语言风格：
    - 专业而友好，保持适当的正式度
    - 逻辑清晰，条理分明
    - 语言简洁，避免冗余
    - 适应用户的专业水平调整表达方
    
    ### 回答结构：
    1. **直接回答**：首先回应用户的核心问题
    2. **详细解释**：提供必要的背景和细节
    3. **实用建议**：给出具体的行动建议
    4. **补充信息**：添加相关的有用信息
    5. **后续支持**：提供进一步帮助的方向
    
    ### 质量标准：
    - 信息准确性：确保提供的信息真实可靠
    - 逻辑一致性：确保回答内容逻辑严密
    - 实用价值：确保回答对用户有实际帮助
    - 安全责任：确保建议不会造成负面影响
    
    ## 执行指引
    基于RIPER-5框架，深入理解用户问题，利用上下文信息，提供专业、准确、实用的回答。始终保持专业性、准确性和安全性，为用户创造最大价值。